Map<String, String> get enUs => {
  'language_change': 'Change Language',
  'english': 'English',
  'hindi': 'Hindi',
  'gujarati': 'Gujarati',
  'purchase_order': 'Purchase Order',
  'design_details': 'Design Details',
  'select_design': 'Select Design',
  'browse_design': 'Browse Design',
  'search_design': 'Search Design',
  'search_design_by': 'Search Design by Name or Number...',
  'design_name': 'Design Name',
  'enter_design_name': 'Enter Design Name',
  'design_number': 'Design Number',
  'enter_design_number': 'Enter Design Number (Ex.: WF-100)',
  'design_image': 'Design Image',
  'tap_to_upload_photo': 'Tap to Upload a Photo',
  'submit_design': 'Submit Design',
  'party_details': 'Party Details',
  'browse_party': "Browse Party",
  'select_party': 'Select Party',
  'search_parties': 'Search Parties',
  'search_party_by': 'Search Parties by Name or GST...',
  'party_name': 'Party Name',
  'enter_party_name': 'Enter Party Name',
  'party_number': 'Party Number',
  'enter_party_number': 'Enter Unique Party Number (EX. WF-100)',
  'gst_number': 'GST Number',
  'enter_gst_number': 'Enter GST Number',
  'phone_number': 'Phone Number',
  'enter_phone_number': 'Enter Phone Number',
  'email': 'Email',
  'enter_email_address': 'Enter Email address',
  'address': 'Address',
  'enter_full_address': 'Enter Full Address',
  'brokers_name': 'Brokers Name',
  'enter_broker_name': 'Enter Broker Name',
  'submit_party': 'Submit Party',
  'create_party': 'Create Party',
  'update_design': 'Update Design',
  'remove_image': 'Remove Image',
  'update_party': 'Update Party',
  'delete_party': 'Delete Party',
  'delete_design': 'Delete Design',
  'party_name_is_mandatory': 'Party Name is Mandatory',
  'party_number_is_mandatory': 'Party Number is Mandatory',
  'delete': 'Delete',

  'design_updated_successfully': 'Design updated successfully.',
  //quality
  'quality_specifications': 'Quality Specifications',
  'panna': 'Panna',
  'enter_panna_width': 'Enter Panna width',
  'panna_is_required': 'Panna is required.',
  'process': 'Process',
  'dyeing_printing': 'e.g., Dyeing, Printing',
  'order_details': 'Order Details',
  'quantity': 'Quantity',
  'enter_total_quantity': 'Enter total quantity',
  'quantity_must_be_greater_than_0': 'Quantity must be greater than 0.',
  'rate': 'Rate',
  'enter_rate_per_unit': 'Enter rate per unit',
  'party_po_number': 'Party PO Number',
  'enter_partys_po_number': 'Enter Party\'s PO number',
  'delivery_date': 'Delivery Date',
  'select_delivery_date': 'Select delivery date',
  'high_priority': 'High Priority',
  'save_order': 'Save Order',

  'pending': 'Pending',
  'in_progress': 'In Process',
  'ready_to_dispatch': 'Ready to Dispatch',
  'completed': 'Completed',
  'customer': 'Customer',
  'customer_id': 'Customer Id',
  'customer_name': 'Customer Name',
  'enter_customer_name': 'Enter Customer Name',

  'edit': 'Edit',
  'home': 'Home',
  'po_list': 'PO List',
  'create_po': 'Create PO',
  'profile': 'Profile',
  'firm_name': 'Firm Name',
  'moved_by': 'Moved By',
  'machine_no': 'Machine No',
  'delivered': 'Delivered',
  'calculator': 'Calculator',
  'warp': 'Warp',
  'weft': 'Weft',
  'labour': 'Labour',
  'total_warp_cost': 'Total Warp Cost',
  'total_weft_cost': 'Total Weft Cost',
  'quality': 'Quality',
  'denier': 'Denier',
  'tar': 'Tar',
  'meter': 'Meter',
  'rate_per_kg': 'Rate Per Kg',
  'save_and_next': 'Save & Next',
  'quality_required': 'Quality Field is required.',
  'denier_required': 'Denier Field is required.',
  'tar_required': 'Tar Field is required.',
  'meter_required': 'Meter Field is required.',
  'rate_per_kg_required': 'Rate per Kg is required.',
  'design_card': 'Design Card',
  'design_card_required': 'Design Card Field is required.',
  'enter_paisa': 'Enter Paisa',
  'paisa': 'Paisa',
  'cost': 'Cost',
  'no_data_found': 'No Data Found',
  'feeder': 'Feeder',
  'pick': 'Pick',
  'panno': 'Panno',
  'atleast_one_feeder_is_required': 'At least one feeder is required.',
  'only_12_feeders_are_allowed': 'Only 12 Feeders are Allowed',

  //users
  'users': 'Users',
  'add_user': 'Add User',
  'edit_user': 'Edit User',
  'user_name': 'User Name',
  'enter_name': 'Enter Name',
  'name_is_mandatory': 'Name is Mandatory',
  'user_created_successfully': 'User created successfully.',
  'user_updated_successfully': 'User updated successfully.',
  'mobile_number': 'Mobile Number',
  'enter_mobile_number': 'Enter Mobile Number',
  'mobile_number_is_mandatory': 'Mobile Number is Mandatory',
  'invalid_mobile_number': 'Invalid Mobile Number',
  'email_address': 'Email Address',
  'enter_email': 'Enter Email',
  'invalid_email_address': 'Invalid Email Address',
  'user_deleted_successfully': 'User deleted successfully.',
  'are_you_sure_you_want_to_delete_user':
      'Are you sure you want to delete user?',
  'no_users_found': 'No users found',

  'logout': 'Logout',
  'confirm_logout': 'Are you sure you want to logout?',
  'cancel': 'Cancel',
  'password': 'Password',
  'enter_password': 'Enter your password',
  'login_with_username_and_password': 'Login',
  'old_password': 'Old Password',
  'new_password': 'New Password',
  'confirm_new_password': 'Confirm New Password',

  'is_active': 'Is Active',
  'name': 'Name',
  'phone': 'Phone',
  'create': 'Create',
  'update': 'Update',
  'edit_user_details': 'Edit User Details',
  'select_role': 'Select Role',
  'user_role': 'User Role',
  'confirm': 'Confirm',
  'no': 'No',

  'order_type': 'Order Type',
  'select_order_type': 'Select Order Type',
  'job_po': 'Job PO',
  'matching': 'Matching',
  'remarks': 'Remarks',
  'firm': 'Firm',
  'job_user': 'Job User',

  'order_quantity': 'Order Quantity',
  'pending_quantity': 'Pending Quantity',
  'in_process_quantity': 'In Process Quantity',
  'ready_to_dispatch_quantity': 'Ready to Dispatch Quantity',
  'completed_quantity': 'Completed Quantity',
  'delivered_quantity': 'Delivered Quantity',
  'note': 'Note',
  'firms': 'Firms',
  'add_firm': 'Add Firm',
  'edit_firm': 'Edit Firm',
  'firm_enter_name': 'Enter Firm Name',
  'firm_name_required': 'Firm Name is required.',
  'delete_firm': 'Delete Firm',
  'are_you_sure_you_want_to_delete_firm':
      'Are you sure you want to delete firm?',
  'history': 'History',
  'updated_at': 'Updated At',
  'user': 'User',
  'no_order_history_found': 'No Order History Found',
  'view_details': 'View Details',
  'order_history': 'Order History',
  'pdf': 'PDF',
  'no_firm_found': 'No Firm Found',
  'change_password': 'Change Password',
  'confirm_password': 'Confirm Password',
  'active': 'Active',
  'inactive': 'Inactive',

  'exit': 'Exit',
  'are_you_sure_you_want_to_exit_app': 'Are you sure you want to exit the app?',

  'please_enter_party_name': 'Please enter party name.',
  'please_enter_party_number': 'Please enter party number.',
  'please_enter_gst_number': 'Please enter GST number.',
  'select': 'Select',
  'garment': 'Garment',
  'sari': 'Sari',
  'select_date': 'Select Date',
  'field_required': 'This field is required.',
  'pending_qty': 'Pending Qty',
  'quantity_cannot_exceed': 'Quantity cannot exceed @type quantity.',
  'update_po_status': 'Update PO Status',
  'move_to': 'Move To (Current Status: @status)',
  'po_number': 'PO Number',
  'order_date': 'Order Date',
  'matching_colors': 'Matching Colors',
  'color': 'Color',
  'created_at': 'Created At',
};
