Map<String, String> get guIn => {
  'language_change': 'ભાષા બદલો',
  'english': 'અંગ્રેજી',
  'hindi': 'હિન્દી',
  'gujarati': 'ગુજરાતી',
  'purchase_order': 'ખરીદ ઓર્ડર',
  'design_details': 'ડિઝાઇન વિગતો',
  'select_design': 'ડિઝાઇન પસંદ કરો',
  'browse_design': 'ડિઝાઇન બ્રાઉઝ કરો',
  'search_design': 'ડિઝાઇન શોધો',
  'search_design_by': 'નામ અથવા નંબર દ્વારા ડિઝાઇન શોધો...',
  'design_name': 'ડિઝાઇનનું નામ',
  'enter_design_name': 'ડિઝાઇનનું નામ દાખલ કરો',
  'design_number': 'ડિઝાઇન નંબર',
  'enter_design_number': 'ડિઝાઇન નંબર દાખલ કરો (દા.ત.: WF-100)',
  'design_image': 'ડિઝાઇન છબી',
  'tap_to_upload_photo': 'ફોટો અપલોડ કરવા માટે ટેપ કરો',
  'submit_design': 'ડિઝાઇન સબમિટ કરો',
  'party_details': 'પાર્ટીની વિગતો',
  'browse_party': "પાર્ટી બ્રાઉઝ કરો",
  'select_party': 'પાર્ટી પસંદ કરો',
  'search_parties': 'પાર્ટીઓ શોધો',
  'search_party_by': 'નામ અથવા GST દ્વારા પાર્ટીઓ શોધો...',
  'party_name': 'પાર્ટીનું નામ',
  'enter_party_name': 'પાર્ટીનું નામ દાખલ કરો',
  'party_number': 'પાર્ટી નંબર',
  'enter_party_number': 'અનન્ય પાર્ટી નંબર દાખલ કરો (દા.ત. WF-100)',
  'gst_number': 'GST નંબર',
  'enter_gst_number': 'GST નંબર દાખલ કરો',
  'phone_number': 'ફોન નંબર',
  'enter_phone_number': 'ફોન નંબર દાખલ કરો',
  'email': 'ઈમેલ',
  'enter_email_address': 'ઈમેલ એડ્રેસ દાખલ કરો',
  'address': 'સરનામું',
  'enter_full_address': 'પૂરું સરનામું દાખલ કરો',
  'brokers_name': 'બ્રોકરનું નામ',
  'enter_broker_name': 'બ્રોકરનું નામ દાખલ કરો',
  'submit_party': 'પાર્ટી સબમિટ કરો',
  'create_party': 'પાર્ટી બનાવો',
  'update_design': 'ડિઝાઇન અપડેટ કરો',
  'remove_image': 'છબી દૂર કરો',
  'update_party': 'પાર્ટી અપડેટ કરો',
  'delete_party': 'પાર્ટી કાઢી નાખો',
  'delete_design': 'ડિઝાઇન કાઢી નાખો',
  'party_name_is_mandatory': 'પાર્ટીનું નામ ફરજિયાત છે',
  'party_number_is_mandatory': 'પાર્ટી નંબર ફરજિયાત છે',
  'delete': 'કાઢી નાખો',

  'quality_specifications': 'ગુણવત્તા સ્પષ્ટીકરણો',
  'panna': 'પન્ના',
  'enter_panna_width': 'પન્નાની પહોળાઈ દાખલ કરો',
  'panna_is_required': 'પન્ના જરૂરી છે.',
  'process': 'પ્રક્રિયા',
  'dyeing_printing': 'દા.ત., રંગાઈ, છાપકામ',
  'order_details': 'ઓર્ડર વિગતો',
  'quantity': 'જથ્થો',
  'enter_total_quantity': 'કુલ જથ્થો દાખલ કરો',
  'quantity_must_be_greater_than_0': 'જથ્થો 0 કરતાં વધુ હોવો જોઈએ.',
  'rate': 'દર',
  'enter_rate_per_unit': 'પ્રતિ એકમ દર દાખલ કરો',
  'party_po_number': 'પાર્ટી પીઓ નંબર',
  'enter_partys_po_number': 'પાર્ટીનો પીઓ નંબર દાખલ કરો',
  'delivery_date': 'ડિલિવરી તારીખ',
  'select_delivery_date': 'ડિલિવરી તારીખ પસંદ કરો',
  'high_priority': 'ઉચ્ચ અગ્રતા',
  'save_order': 'ઓર્ડર સાચવો',

  'pending': 'બાકી',
  'in_progress': 'પ્રગતિમાં',
  'ready_to_dispatch': 'રવાના થવા માટે તૈયાર',
  'completed': 'પૂર્ણ',
  'customer': 'ગ્રાહક',
  'customer_id': 'ગ્રાહક આઈડી',

  'edit': 'સંપાદિત કરો',
  'home': 'હોમ',
  'po_list': 'પીઓ યાદી',
  'create_po': 'પીઓ બનાવો',
  'profile': 'પ્રોફાઇલ',

  'firm_name': 'પેઢીનું નામ',
  'moved_by': 'દ્વારા ખસેડાયું',
  'machine_no': 'મશીન નંબર',

  'delivered': 'પહોંચાડાયું',
  'calculator': 'કેલ્ક્યુલેટર',

  'warp': 'તાણ',
  'weft': 'વણાટ',
  'labour': 'મજૂરી',
  'total_warp_cost': 'કુલ તાણ ખર્ચ',
  'total_weft_cost': 'કુલ વણાટ ખર્ચ',
  'quality': 'ગુણવત્તા',
  'denier': 'ડેનિયર',
  'tar': 'તાર',
  'meter': 'મીટર',
  'rate_per_kg': 'પ્રતિ કિલોગ્રામ દર',
  'save_and_next': 'સાચવો અને આગળ',

  'quality_required': 'ગુણવત્તા ક્ષેત્ર જરૂરી છે.',
  'denier_required': 'ડેનિયર ક્ષેત્ર જરૂરી છે.',
  'tar_required': 'તાર ક્ષેત્ર જરૂરી છે.',
  'meter_required': 'મીટર ક્ષેત્ર જરૂરી છે.',
  'rate_per_kg_required': 'પ્રતિ કિલોગ્રામ દર જરૂરી છે.',
  'design_card': 'ડિઝાઇન કાર્ડ',
  'design_card_required': 'ડિઝાઇન કાર્ડ ક્ષેત્ર જરૂરી છે.',
  'enter_paisa': 'પૈસા દાખલ કરો',
  'paisa': 'પૈસા',
  'cost': 'ખર્ચ',
  'no_data_found': 'કોઈ ડેટા મળ્યો નથી',
  'feeder': 'ફીડર',
  'pick': 'પિક',
  'panno': 'પન્નો',
  'atleast_one_feeder_is_required': 'કમ સે કમ એક ફીડર જરૂરી છે.',
  'only_12_feeders_are_allowed': 'ફક્ત 12 ફીડર્સની મંજૂરી છે.',
  'users': 'વપરાશકર્તાઓ',
  'add_user': 'વપરાશકર્તા ઉમેરો',
  'edit_user': 'વપરાશકર્તા સંપાદિત કરો',

  'logout': 'લૉગ આઉટ',
  'confirm_logout': 'શું તમે ખરેખર લૉગ આઉટ કરવા માંગો છો?',
  'cancel': 'રદ કરો',
  'password': 'પાસવર્ડ',
  'enter_password': 'તમારો પાસવર્ડ દાખલ કરો',
  'login_with_username_and_password': 'લૉગિન કરો',
  'is_active': 'સક્રિય છે',
  'name': 'નામ',
  'phone': 'ફોન',
  'create': 'બનાવો',
  'update': 'અપડેટ કરો',
  'edit_user_details': 'વપરાશકર્તા વિગતો સંપાદિત કરો',
  'select_role': 'ભૂમિકા પસંદ કરો',
  'user_role': 'વપરાશકર્તા ભૂમિકા',
  'confirm': 'પુષ્ટિ કરો',
  'no': 'ના',
  'order_type': 'ઓર્ડર પ્રકાર',
  'job_po': 'જોબ પીઓ',
  'order_quantity': 'ઓર્ડર જથ્થો',
  'pending_quantity': 'બાકી જથ્થો',
  'in_process_quantity': 'પ્રગતિમાં જથ્થો',
  'ready_to_dispatch_quantity': 'રવાના થવા માટે તૈયાર જથ્થો',
  'completed_quantity': 'પૂર્ણ જથ્થો',
  'delivered_quantity': 'પહોંચાડાયેલું જથ્થો',
  'note': 'નોંધ',
  'firms': 'ફર્મ',
  'add_firm': 'ફર્મ ઉમેરો',
  'edit_firm': 'ફર્મ સંપાદિત કરો',
  'firm_enter_name': 'ફર્મનું નામ દાખલ કરો',
  'firm_name_required': 'ફર્મનું નામ જરૂરી છે.',
  'delete_firm': 'ફર્મ કાઢી નાખો',
  'are_you_sure_you_want_to_delete_firm':
      'શું તમે ખરેખર ફર્મ કાઢી નાખવા માંગો છો?',
  'history': 'ઇતિહાસ',
  'updated_at': 'અપડેટેડ એટ',
  'order_history': 'ઓર્ડર ઇતિહાસ',
  'user': 'વપરાશકર્તા',
  'no_order_history_found': 'કોઈ ઓર્ડર ઇતિહાસ મળ્યો નથી',
  'view_details': 'વિગતો જુઓ',
  'pdf': 'પીડીએફ',
  'no_firm_found': 'કોઈ ફર્મ મળ્યો નથી',
  'change_password': 'પાસવર્ડ બદલો',
  'confirm_password': 'પાસવર્ડની પુષ્ટિ કરો',
  'active': 'સક્રિય',
  'inactive': 'નિષ્ક્રિય',
  'old_password': 'જૂનો પાસવર્ડ',
  'new_password': 'નવો પાસવર્ડ',
  'confirm_new_password': 'નવા પાસવર્ડની પુષ્ટિ કરો',
  'exit': 'બહાર નીકળો',
  'are_you_sure_you_want_to_exit_app':
      'શું તમે ખરેખર એપ્લિકેશનમાંથી બહાર નીકળવા માંગો છો?',
  'design_updated_successfully': 'ડિઝાઇન સફળતાપૂર્વક અપડેટ થઈ ગઈ છે.',
  'please_enter_party_name': 'કૃપા કરીને પાર્ટીનું નામ દાખલ કરો.',
  'please_enter_party_number': 'કૃપા કરીને પાર્ટી નંબર દાખલ કરો.',
  'please_enter_gst_number': 'કૃપા કરીને GST નંબર દાખલ કરો.',
  'select': 'પસંદ કરો',
  'garment': 'વસ્ત્ર',
  'sari': 'સાડી',
  'select_date': 'તારીખ પસંદ કરો',
  'field_required': 'આ ફીલ્ડ જરૂરી છે.',
  'remarks': 'ટિપ્પણીઓ',
  'select_order_type': 'ઓર્ડર પ્રકાર પસંદ કરો',
  'matching': 'મિલાન',
  'firm': 'ફર્મ',
  'job_user': 'જોબ વપરાશકર્તા',
  'pending_qty': 'બાકી જથ્થો',
  'quantity_cannot_exceed': 'જથ્થો @type જથ્થા કરતાં વધુ ન હોઈ શકે.',
  'update_po_status': 'પીઓ સ્થિતિ અપડેટ કરો',
  'move_to': 'સ્થાનાંતરિત કરો (વર્તમાન સ્થિતિ: @status)',
  'po_number': 'પીઓ નંબર',
  'order_date': 'ઓર્ડર તારીખ',
  'matching_colors': 'મેચિંગ કલર્સ',
  'color': 'કલર',
  'created_at': 'બનાવેલ તારીખ',
};
