Map<String, String> get hiIn => {
  'language_change': 'भाषा बदलें',
  'english': 'अंग्रेज़ी',
  'hindi': 'हिंदी',
  'gujarati': 'ગુજરાતી',
  'purchase_order': 'खरीद फरोख्त',
  'design_details': 'डिज़ाइन विवरण',
  'select_design': 'डिज़ाइन चुनें',
  'browse_design': 'डिज़ाइन ब्राउज़ करें',
  'search_design': 'डिज़ाइन खोजें',
  'search_design_by': 'नाम या नंबर से डिज़ाइन खोजें...',
  'design_name': 'डिज़ाइन का नाम',
  'enter_design_name': 'डिज़ाइन का नाम दर्ज करें',
  'design_number': 'डिज़ाइन नंबर',
  'enter_design_number': 'डिज़ाइन नंबर दर्ज करें (उदा.: WF-100)',
  'design_image': 'डिज़ाइन की छवि',
  'tap_to_upload_photo': 'फोटो अपलोड करने के लिए टैप करें',
  'submit_design': 'डिज़ाइन सबमिट करें',
  'party_details': 'पार्टी का विवरण',
  'browse_party': "पार्टी ब्राउज़ करें",
  'select_party': 'पार्टी चुनें',
  'search_parties': 'पार्टी खोजें',
  'search_party_by': 'नाम या GST द्वारा पार्टी खोजें...',
  'party_name': 'पार्टी का नाम',
  'enter_party_name': 'पार्टी का नाम दर्ज करें',
  'party_number': 'पार्टी नंबर',
  'enter_party_number': 'पार्टी नंबर दर्ज करें (उदा.: WF-100)',
  'gst_number': 'GST नंबर',
  'enter_gst_number': 'GST नंबर दर्ज करें',
  'phone_number': 'फोन नंबर',
  'enter_phone_number': 'फोन नंबर दर्ज करें',
  'email': 'ईमेल',
  'enter_email_address': 'ईमेल पता दर्ज करें',
  'address': 'पता',
  'enter_full_address': 'पूरा पता दर्ज करें',
  'brokers_name': 'ब्रोकर का नाम',
  'enter_broker_name': 'ब्रोकर का नाम दर्ज करें',
  'submit_party': 'पार्टी सबमिट करें',
  'create_party': 'पार्टी बनाएं',
  'update_design': 'डिज़ाइन अपडेट करें',
  'remove_image': 'छवि निकालें',
  'update_party': 'पार्टी अपडेट करें',
  'delete_party': 'पार्टी हटाएं',
  'delete_design': 'डिज़ाइन हटाएं',
  'party_name_is_mandatory': 'पार्टी का नाम अनिवार्य है',
  'party_number_is_mandatory': 'पार्टी नंबर अनिवार्य है',
  'delete': 'हटाएं',

  'quality_specifications': 'गुणवत्ता विनिर्देश',
  'panna': 'पन्ना',
  'enter_panna_width': 'पन्ना की चौड़ाई दर्ज करें',
  'panna_is_required': 'पन्ना आवश्यक है।',
  'process': 'प्रक्रिया',
  'dyeing_printing': 'जैसे, रंगाई, छपाई',
  'order_details': 'ऑर्डर विवरण',
  'quantity': 'मात्रा',
  'enter_total_quantity': 'कुल मात्रा दर्ज करें',
  'quantity_must_be_greater_than_0': 'मात्रा 0 से अधिक होनी चाहिए।',
  'rate': 'दर',
  'enter_rate_per_unit': 'प्रति इकाई दर दर्ज करें',
  'party_po_number': 'पार्टी पीओ नंबर',
  'enter_partys_po_number': 'पार्टी का पीओ नंबर दर्ज करें',
  'delivery_date': 'डिलीवरी की तारीख',
  'select_delivery_date': 'डिलीवरी की तारीख चुनें',
  'high_priority': 'उच्च प्राथमिकता',
  'save_order': 'ऑर्डर सहेजें',

  'pending': 'लंबित',
  'in_progress': 'प्रगति पर',
  'ready_to_dispatch': 'डिस्पैच के लिए तैयार',
  'completed': 'पूर्ण',
  'customer': 'ग्राहक',
  'customer_id': 'ग्राहक आईडी',

  'edit': 'संपादित करें',
  'home': 'होम',
  'po_list': 'पीओ सूची',
  'create_po': 'पीओ बनाएं',
  'profile': 'प्रोफ़ाइल',

  'firm_name': 'फर्म का नाम',
  'moved_by': 'द्वारा ले जाया गया',
  'machine_no': 'मशीन नंबर',
  'delivered': 'वितरित',
  'calculator': 'कैलकुलेटर',

  'warp': 'ताना',
  'weft': 'बाना',
  'labour': 'श्रम',
  'total_warp_cost': 'कुल ताना लागत',
  'total_weft_cost': 'कुल बाना लागत',
  'quality': 'गुणवत्ता',
  'denier': 'डेनियर',
  'tar': 'तार',
  'meter': 'मीटर',
  'rate_per_kg': 'प्रति किलो दर',
  'save_and_next': 'सहेजें और अगला',
  'quality_required': 'गुणवत्ता फ़ील्ड आवश्यक है।',
  'denier_required': 'डेनियर फ़ील्ड आवश्यक है।',
  'tar_required': 'तार फ़ील्ड आवश्यक है।',
  'meter_required': 'मीटर फ़ील्ड आवश्यक है।',
  'rate_per_kg_required': 'प्रति किलो दर आवश्यक है।',
  'design_card': 'डिज़ाइन कार्ड',
  'design_card_required': 'डिज़ाइन कार्ड फ़ील्ड आवश्यक है।',
  'enter_paisa': 'पैसा दर्ज करें',
  'paisa': 'पैसा',
  'cost': 'लागत',
  'no_data_found': 'कोई डेटा नहीं मिला',
  'feeder': 'फीडर',
  'pick': 'पिक',
  'panno': 'पन्नो',
  'atleast_one_feeder_is_required': 'कम से कम एक फीडर आवश्यक है।',
  'only_12_feeders_are_allowed': 'केवल 12 फीडर की अनुमति है।',
  'users': 'उपयोगकर्ता',
  'add_user': 'उपयोगकर्ता जोड़ें',
  'edit_user': 'उपयोगकर्ता संपादित करें',

  'logout': 'लॉग आउट',
  'confirm_logout': 'क्या आप वाकई लॉग आउट करना चाहते हैं?',
  'cancel': 'रद्द करें',
  'password': 'पासवर्ड',
  'enter_password': 'अपना पासवर्ड दर्ज करें',
  'login_with_username_and_password': 'लॉगिन',
  'is_active': 'सक्रिय है',
  'name': 'नाम',
  'phone': 'फोन',
  'create': 'बनाएं',
  'update': 'अपडेट करें',
  'edit_user_details': 'उपयोगकर्ता विवरण संपादित करें',
  'select_role': 'भूमिका चुनें',
  'user_role': 'उपयोगकर्ता भूमिका',
  'confirm': 'पुष्टि करें',
  'no': 'नहीं',
  'order_type': 'ऑर्डर प्रकार',
  'job_po': 'जॉब पीओ',
  'order_quantity': 'ऑर्डर मात्रा',
  'pending_quantity': 'लंबित मात्रा',
  'in_process_quantity': 'प्रगति में मात्रा',

  'ready_to_dispatch_quantity': 'डिस्पैच के लिए तैयार मात्रा',
  'completed_quantity': 'पूर्ण मात्रा',
  'delivered_quantity': 'वितरित मात्रा',
  'note': 'नोट',

  'firms': 'फर्म',
  'add_firm': 'फर्म जोड़ें',
  'edit_firm': 'फर्म संपादित करें',
  'firm_enter_name': 'फर्म का नाम दर्ज करें',
  'firm_name_required': 'फर्म का नाम आवश्यक है।',

  'delete_firm': 'फर्म हटाएं',
  'are_you_sure_you_want_to_delete_firm': 'क्या आप वाकई फर्म हटाना चाहते हैं?',
  'history': 'इतिहास',
  'updated_at': 'अपडेटेड एट',

  'order_history': 'ऑर्डर इतिहास',
  'user': 'उपयोगकर्ता',
  'no_order_history_found': 'कोई ऑर्डर इतिहास नहीं मिला',
  'view_details': 'विवरण देखें',
  'pdf': 'पीडीएफ',
  'no_firm_found': 'कोई फर्म नहीं मिली',
  'change_password': 'पासवर्ड बदलें',
  'confirm_password': 'पासवर्ड की पुष्टि करें',
  'active': 'सक्रिय',
  'inactive': 'निष्क्रिय',
  'old_password': 'पुराना पासवर्ड',
  'new_password': 'नया पासवर्ड',
  'confirm_new_password': 'नए पासवर्ड की पुष्टि करें',
  'exit': 'बाहर निकलें',
  'are_you_sure_you_want_to_exit_app':
      'क्या आप वाकई ऐप से बाहर निकलना चाहते हैं?',
  'design_updated_successfully': 'डिज़ाइन सफलतापूर्वक अपडेट किया गया।',
  'please_enter_party_name': 'कृपया पार्टी का नाम दर्ज करें।',
  'please_enter_party_number': 'कृपया पार्टी नंबर दर्ज करें।',
  'please_enter_gst_number': 'कृपया GST नंबर दर्ज करें।',
  'select': 'चुनें',
  'garment': 'परिधान',
  'sari': 'साड़ी',
  'select_date': 'तारीख चुनें',
  'field_required': 'यह फ़ील्ड आवश्यक है।',
  'remarks': 'टिप्पणियाँ',
  'select_order_type': 'ऑर्डर प्रकार चुनें',
  'matching': 'मिलान',
  'firm': 'फर्म',
  'job_user': 'जॉब उपयोगकर्ता',
  'pending_qty': 'लंबित मात्रा',
  'quantity_cannot_exceed': 'मात्रा @type मात्रा से अधिक नहीं हो सकती।',
  'update_po_status': 'पीओ स्थिति अपडेट करें',
  'move_to': 'स्थानांतरित करें (वर्तमान स्थिति: @status)',
  'po_number': 'पीओ नंबर',
  'order_date': 'ऑर्डर तारीख',
  'matching_colors': 'मिलान रंग',
  'color': 'रंग',
  'created_at': 'बनाई गई तारीख',
};
