import 'package:get/get.dart';

class AppTranslations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en_US': {
      'language_change': 'Change Language',
      'english': 'English',
      'hindi': 'Hindi',
      'gujarati': 'Gujarati',
      'purchase_order': 'Purchase Order',
      'design_details': 'Design Details',
      'select_design': 'Select Design',
      'browse_design': 'Browse Design',
      'search_design': 'Search Design',
      'search_design_by': 'Search Design by Name or Number...',
      'design_name': 'Design Name',
      'enter_design_name': 'Enter Design Name',
      'design_number': 'Design Number',
      'enter_design_number': 'Enter Design Number (Ex.: WF-100)',
      'design_image': 'Design Image',
      'tap_to_upload_photo': 'Tap to Upload a Photo',
      'submit_design': 'Submit Design',
      'party_details': 'Party Details',
      'browse_party': "Browse Party",
      'select_party': 'Select Party',
      'search_parties': 'Search Parties',
      'search_party_by': 'Search Parties by Name or GST...',
      'party_name': 'Party Name',
      'enter_party_name': 'Enter Party Name',
      'party_number': 'Party Number',
      'enter_party_number': 'Enter Unique Party Number (EX. WF-100)',
      'gst_number': 'GST Number',
      'enter_gst_number': 'Enter GST Number',
      'phone_number': 'Phone Number',
      'enter_phone_number': 'Enter Phone Number',
      'email': 'Email',
      'enter_email_address': 'Enter Email address',
      'address': 'Address',
      'enter_full_address': 'Enter Full Address',
      'brokers_name': 'Brokers Name',
      'enter_broker_name': 'Enter Broker Name',
      'submit_party': 'Submit Party',
      'create_party': 'Create Party',
      'update_design': 'Update Design',
      'remove_image': 'Remove Image',
      'update_party': 'Update Party',
      'delete_party': 'Delete Party',
      'delete_design': 'Delete Design',
      'party_name_is_mandatory': 'Party Name is Mandatory',
      'party_number_is_mandatory': 'Party Number is Mandatory',
      'delete': 'Delete',
      //quality
      'quality_specifications': 'Quality Specifications',
      'panna': 'Panna',
      'enter_panna_width': 'Enter Panna width',
      'panna_is_required': 'Panna is required.',
      'process': 'Process',
      'dyeing_printing': 'e.g., Dyeing, Printing',
      'order_details': 'Order Details',
      'quantity': 'Quantity',
      'enter_total_quantity': 'Enter total quantity',
      'quantity_must_be_greater_than_0': 'Quantity must be greater than 0.',
      'rate': 'Rate',
      'enter_rate_per_unit': 'Enter rate per unit',
      'party_po_number': 'Party PO Number',
      'enter_partys_po_number': 'Enter Party\'s PO number',
      'delivery_date': 'Delivery Date',
      'select_delivery_date': 'Select delivery date',
      'high_priority': 'High Priority',
      'save_order': 'Save Order',

      'pending': 'Pending',
      'in_progress': 'In Process',
      'ready_to_dispatch': 'Ready to Dispatch',
      'completed': 'Completed',
      'customer': 'Customer',
      'customer_id': 'Customer Id',

      'edit': 'Edit',
      'home': 'Home',
      'po_list': 'PO List',
      'create_po': 'Create PO',
      'profile': 'Profile',
      'firm_name': 'Firm Name',
      'moved_by': 'Moved By',
      'machine_no': 'Machine No',
    },
    'hi_IN': {
      'language_change': 'भाषा बदलें',
      'english': 'अंग्रेज़ी',
      'hindi': 'हिंदी',
      'gujarati': 'ગુજરાતી',
      'purchase_order': 'खरीद फरोख्त',
      'design_details': 'डिज़ाइन विवरण',
      'select_design': 'डिज़ाइन चुनें',
      'browse_design': 'डिज़ाइन ब्राउज़ करें',
      'search_design': 'डिज़ाइन खोजें',
      'search_design_by': 'नाम या नंबर से डिज़ाइन खोजें...',
      'design_name': 'डिज़ाइन का नाम',
      'enter_design_name': 'डिज़ाइन का नाम दर्ज करें',
      'design_number': 'डिज़ाइन नंबर',
      'enter_design_number': 'डिज़ाइन नंबर दर्ज करें (उदा.: WF-100)',
      'design_image': 'डिज़ाइन की छवि',
      'tap_to_upload_photo': 'फोटो अपलोड करने के लिए टैप करें',
      'submit_design': 'डिज़ाइन सबमिट करें',
      'party_details': 'पार्टी का विवरण',
      'browse_party': "પાર્ટી બ્રાઉઝ કરો",
      'select_party': 'પાર્ટી પસંદ કરો',
      'search_parties': 'પાર્ટીઓ શોધો',
      'search_party_by': 'નામ અથવા GST દ્વારા પાર્ટીઓ શોધો...',
      'party_name': 'પાર્ટીનું નામ',
      'enter_party_name': 'પાર્ટીનું નામ દાખલ કરો',
      'party_number': 'પાર્ટી નંબર',
      'enter_party_number': 'અનન્ય પાર્ટી નંબર દાખલ કરો (દા.ત. WF-100)',
      'gst_number': 'GST નંબર',
      'enter_gst_number': 'GST નંબર દાખલ કરો',
      'phone_number': 'ફોન નંબર',
      'enter_phone_number': 'ફોન નંબર દાખલ કરો',
      'email': 'ઈમેલ',
      'enter_email_address': 'ઈમેલ એડ્રેસ દાખલ કરો',
      'address': 'સરનામું',
      'enter_full_address': 'પૂરું સરનામું દાખલ કરો',
      'brokers_name': 'બ્રોકરનું નામ',
      'enter_broker_name': 'બ્રોકરનું નામ દાખલ કરો',
      'submit_party': 'પાર્ટી સબમિટ કરો',
      'create_party': 'પાર્ટી બનાવો',
      'update_design': 'डिज़ाइन अपडेट करें',
      'remove_image': 'छवि निकालें',
      'update_party': 'पार्टी अपडेट करें',
      'delete_party': 'पार्टी हटाएं',
      'delete_design': 'डिज़ाइन हटाएं',
      'party_name_is_mandatory': 'पार्टी का नाम अनिवार्य है',
      'party_number_is_mandatory': 'पार्टी नंबर अनिवार्य है',
      'delete': 'हटाएं',

      'quality_specifications': 'गुणवत्ता विनिर्देश',
      'panna': 'पन्ना',
      'enter_panna_width': 'पन्ना की चौड़ाई दर्ज करें',
      'panna_is_required': 'पन्ना आवश्यक है।',
      'process': 'प्रक्रिया',
      'dyeing_printing': 'जैसे, रंगाई, छपाई',
      'order_details': 'ऑर्डर विवरण',
      'quantity': 'मात्रा',
      'enter_total_quantity': 'कुल मात्रा दर्ज करें',
      'quantity_must_be_greater_than_0': 'मात्रा 0 से अधिक होनी चाहिए।',
      'rate': 'दर',
      'enter_rate_per_unit': 'प्रति इकाई दर दर्ज करें',
      'party_po_number': 'पार्टी पीओ नंबर',
      'enter_partys_po_number': 'पार्टी का पीओ नंबर दर्ज करें',
      'delivery_date': 'डिलीवरी की तारीख',
      'select_delivery_date': 'डिलीवरी की तारीख चुनें',
      'high_priority': 'उच्च प्राथमिकता',
      'save_order': 'ऑर्डर सहेजें',

      'pending': 'लंबित',
      'in_progress': 'प्रगति पर',
      'ready_to_dispatch': 'डिस्पैच के लिए तैयार',
      'completed': 'पूर्ण',
      'customer': 'ग्राहक',
      'customer_id': 'ग्राहक आईडी',

      'edit': 'संपादित करें',
      'home': 'होम',
      'po_list': 'पीओ सूची',
      'create_po': 'पीओ बनाएं',
      'profile': 'प्रोफ़ाइल',

      'firm_name': 'फर्म का नाम',
      'moved_by': 'द्वारा ले जाया गया',
      'machine_no': 'मशीन नंबर',
    },
    'gu_IN': {
      'language_change': 'ભાષા બદલો',
      'english': 'અંગ્રેજી',
      'hindi': 'હિન્દી',
      'gujarati': 'ગુજરાતી',
      'purchase_order': 'ખરીદ ઓર્ડર',
      'design_details': 'ડિઝાઇન વિગતો',
      'select_design': 'ડિઝાઇન પસંદ કરો',
      'browse_design': 'ડિઝાઇન બ્રાઉઝ કરો',
      'search_design': 'ડિઝાઇન શોધો',
      'search_design_by': 'નામ અથવા નંબર દ્વારા ડિઝાઇન શોધો...',
      'design_name': 'ડિઝાઇનનું નામ',
      'enter_design_name': 'ડિઝાઇનનું નામ દાખલ કરો',
      'design_number': 'ડિઝાઇન નંબર',
      'enter_design_number': 'ડિઝાઇન નંબર દાખલ કરો (દા.ત.: WF-100)',
      'design_image': 'ડિઝાઇન છબી',
      'tap_to_upload_photo': 'ફોટો અપલોડ કરવા માટે ટેપ કરો',
      'submit_design': 'ડિઝાઇન સબમિટ કરો',
      'party_details': 'પાર્ટીની વિગતો',
      'browse_party': "પાર્ટી બ્રાઉઝ કરો",
      'select_party': 'પાર્ટી પસંદ કરો',
      'search_parties': 'પાર્ટીઓ શોધો',
      'search_party_by': 'નામ અથવા GST દ્વારા પાર્ટીઓ શોધો...',
      'party_name': 'પાર્ટીનું નામ',
      'enter_party_name': 'પાર્ટીનું નામ દાખલ કરો',
      'party_number': 'પાર્ટી નંબર',
      'enter_party_number': 'અનન્ય પાર્ટી નંબર દાખલ કરો (દા.ત. WF-100)',
      'gst_number': 'GST નંબર',
      'enter_gst_number': 'GST નંબર દાખલ કરો',
      'phone_number': 'ફોન નંબર',
      'enter_phone_number': 'ફોન નંબર દાખલ કરો',
      'email': 'ઈમેલ',
      'enter_email_address': 'ઈમેલ એડ્રેસ દાખલ કરો',
      'address': 'સરનામું',
      'enter_full_address': 'પૂરું સરનામું દાખલ કરો',
      'brokers_name': 'બ્રોકરનું નામ',
      'enter_broker_name': 'બ્રોકરનું નામ દાખલ કરો',
      'submit_party': 'પાર્ટી સબમિટ કરો',
      'create_party': 'પાર્ટી બનાવો',
      'update_design': 'ડિઝાઇન અપડેટ કરો',
      'remove_image': 'છબી દૂર કરો',
      'update_party': 'પાર્ટી અપડેટ કરો',
      'delete_party': 'પાર્ટી કાઢી નાખો',
      'delete_design': 'ડિઝાઇન કાઢી નાખો',
      'party_name_is_mandatory': 'પાર્ટીનું નામ ફરજિયાત છે',
      'party_number_is_mandatory': 'પાર્ટી નંબર ફરજિયાત છે',
      'delete': 'કાઢી નાખો',

      'quality_specifications': 'ગુણવત્તા સ્પષ્ટીકરણો',
      'panna': 'પન્ના',
      'enter_panna_width': 'પન્નાની પહોળાઈ દાખલ કરો',
      'panna_is_required': 'પન્ના જરૂરી છે.',
      'process': 'પ્રક્રિયા',
      'dyeing_printing': 'દા.ત., રંગાઈ, છાપકામ',
      'order_details': 'ઓર્ડર વિગતો',
      'quantity': 'જથ્થો',
      'enter_total_quantity': 'કુલ જથ્થો દાખલ કરો',
      'quantity_must_be_greater_than_0': 'જથ્થો 0 કરતાં વધુ હોવો જોઈએ.',
      'rate': 'દર',
      'enter_rate_per_unit': 'પ્રતિ એકમ દર દાખલ કરો',
      'party_po_number': 'પાર્ટી પીઓ નંબર',
      'enter_partys_po_number': 'પાર્ટીનો પીઓ નંબર દાખલ કરો',
      'delivery_date': 'ડિલિવરી તારીખ',
      'select_delivery_date': 'ડિલિવરી તારીખ પસંદ કરો',
      'high_priority': 'ઉચ્ચ અગ્રતા',
      'save_order': 'ઓર્ડર સાચવો',

      'pending': 'બાકી',
      'in_progress': 'પ્રગતિમાં',
      'ready_to_dispatch': 'રવાના થવા માટે તૈયાર',
      'completed': 'પૂર્ણ',
      'customer': 'ગ્રાહક',
      'customer_id': 'ગ્રાહક આઈડી',

      'edit': 'સંપાદિત કરો',
      'home': 'હોમ',
      'po_list': 'પીઓ યાદી',
      'create_po': 'પીઓ બનાવો',
      'profile': 'પ્રોફાઇલ',

      'firm_name': 'પેઢીનું નામ',
      'moved_by': 'દ્વારા ખસેડાયું',
      'machine_no': 'મશીન નંબર',
    },
  };
}
