import 'package:get/get.dart';

class AppTranslations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en_US': {
      'language_change': 'Change Language',
      'english': 'English',
      'hindi': 'Hindi',
      'gujarati': 'Gujarati',
      'purchase_order': 'Purchase Order',
      'design_details': 'Design Details',
      'select_design': 'Select Design',
      'browse_design': 'Browse Design',
      'search_design': 'Search Design',
      'search_design_by': 'Search Design by Name or Number...',
      'design_name': 'Design Name',
      'enter_design_name': 'Enter Design Name',
      'design_number': 'Design Number',
      'enter_design_number': 'Enter Design Number (Ex.: WF-100)',
      'design_image': 'Design Image',
      'tap_to_upload_photo': 'Tap to Upload a Photo',
      'submit_design': 'Submit Design',
      'party_details': 'Party Details',
      'browse_party': "Browse Party",
      'select_party': 'Select Party',
      'search_parties': 'Search Parties',
      'search_party_by': 'Search Parties by Name or GST...',
      'party_name': 'Party Name',
      'enter_party_name': 'Enter Party Name',
      'party_number': 'Party Number',
      'enter_party_number': 'Enter Unique Party Number (EX. WF-100)',
      'gst_number': 'GST Number',
      'enter_gst_number': 'Enter GST Number',
      'phone_number': 'Phone Number',
      'enter_phone_number': 'Enter Phone Number',
      'email': 'Email',
      'enter_email_address': 'Enter Email address',
      'address': 'Address',
      'enter_full_address': 'Enter Full Address',
      'brokers_name': 'Brokers Name',
      'enter_broker_name': 'Enter Broker Name',
      'submit_party': 'Submit Party',
      'create_party': 'Create Party',
      'update_design': 'Update Design',
      'remove_image': 'Remove Image',
      'update_party': 'Update Party',
      'delete_party': 'Delete Party',
      'delete_design': 'Delete Design',
      'party_name_is_mandatory': 'Party Name is Mandatory',
      'party_number_is_mandatory': 'Party Number is Mandatory',
      'delete': 'Delete',
      //quality
      'quality_specifications': 'Quality Specifications',
      'panna': 'Panna',
      'enter_panna_width': 'Enter Panna width',
      'panna_is_required': 'Panna is required.',
      'process': 'Process',
      'dyeing_printing': 'e.g., Dyeing, Printing',
      'order_details': 'Order Details',
      'quantity': 'Quantity',
      'enter_total_quantity': 'Enter total quantity',
      'quantity_must_be_greater_than_0': 'Quantity must be greater than 0.',
      'rate': 'Rate',
      'enter_rate_per_unit': 'Enter rate per unit',
      'party_po_number': 'Party PO Number',
      'enter_partys_po_number': 'Enter Party\'s PO number',
      'delivery_date': 'Delivery Date',
      'select_delivery_date': 'Select delivery date',
      'high_priority': 'High Priority',
      'save_order': 'Save Order',

      'pending': 'Pending',
      'in_progress': 'In Process',
      'ready_to_dispatch': 'Ready to Dispatch',
      'completed': 'Completed',
      'customer': 'Customer',
      'customer_id': 'Customer Id',

      'edit': 'Edit',
      'home': 'Home',
      'po_list': 'PO List',
      'create_po': 'Create PO',
      'profile': 'Profile',
      'firm_name': 'Firm Name',
      'moved_by': 'Moved By',
      'machine_no': 'Machine No',
      'delivered': 'Delivered',
      'calculator': 'Calculator',
      'warp': 'Warp',
      'weft': 'Weft',
      'labour': 'Labour',
      'total_warp_cost': 'Total Warp Cost',
      'quality': 'Quality',
      'denier': 'Denier',
      'tar': 'Tar',
      'meter': 'Meter',
      'rate_per_kg': 'Rate Per Kg',
      'save_and_next': 'Save & Next',
      'quality_required': 'Quality Field is required.',
      'denier_required': 'Denier Field is required.',
      'tar_required': 'Tar Field is required.',
      'meter_required': 'Meter Field is required.',
      'rate_per_kg_required': 'Rate per Kg is required.',
      'design_card': 'Design Card',
      'design_card_required': 'Design Card Field is required.',
      'enter_paisa': 'Enter Paisa',
      'paisa': 'Paisa',
      'cost': 'Cost',
      'no_data_found': 'No Data Found',
      'feeder': 'Feeder',
      'pick': 'Pick',
      'panno': 'Panno',
      'atleast_one_feeder_is_required': 'At least one feeder is required.',
      'only_12_feeders_are_allowed': 'Only 12 Feeders are Allowed',

      //users
      'users': 'Users',
      'add_user': 'Add User',
      'edit_user': 'Edit User',
      'user_name': 'User Name',
      'enter_name': 'Enter Name',
      'name_is_mandatory': 'Name is Mandatory',
      'user_created_successfully': 'User created successfully.',
      'user_updated_successfully': 'User updated successfully.',
      'mobile_number': 'Mobile Number',
      'enter_mobile_number': 'Enter Mobile Number',
      'mobile_number_is_mandatory': 'Mobile Number is Mandatory',
      'invalid_mobile_number': 'Invalid Mobile Number',
      'email_address': 'Email Address',
      'enter_email': 'Enter Email',
      'invalid_email_address': 'Invalid Email Address',
      'user_deleted_successfully': 'User deleted successfully.',
      'are_you_sure_you_want_to_delete_user':
          'Are you sure you want to delete user?',
      'no_users_found': 'No users found',

      'logout': 'Logout',
      'confirm_logout': 'Are you sure you want to logout?',
      'cancel': 'Cancel',
      'password': 'Password',
      'enter_password': 'Enter your password',
      'login_with_username_and_password': 'Login with User Name and Password.',

      'is_active': 'Is Active',
      'name': 'Name',
      'phone': 'Phone',
      'create': 'Create',
      'update': 'Update',
      'edit_user_details': 'Edit User Details',
      'select_role': 'Select Role',
      'user_role': 'User Role',
      'confirm': 'Confirm',
      'no': 'No',

      'order_type': 'Order Type',
      'select_order_type': 'Select Order Type',
      'job_po': 'Job PO',
      'matching': 'Matching',
      'remarks': 'Remarks',
      'firm': 'Firm',
      'job_user': 'Job User',

      'order_quantity': 'Order Quantity',
      'pending_quantity': 'Pending Quantity',
      'in_process_quantity': 'In Process Quantity',
      'ready_to_dispatch_quantity': 'Ready to Dispatch Quantity',
      'completed_quantity': 'Completed Quantity',
      'delivered_quantity': 'Delivered Quantity',
      'note': 'Note',
      'firms': 'Firms',
      'add_firm': 'Add Firm',
      'edit_firm': 'Edit Firm',
      'firm_enter_name': 'Enter Firm Name',
      'firm_name_required': 'Firm Name is required.',
      'delete_firm': 'Delete Firm',
      'are_you_sure_you_want_to_delete_firm':
          'Are you sure you want to delete firm?',
      'history': 'History',
      'updated_at': 'Updated At',
      'user': 'User',
    },
    'hi_IN': {
      'language_change': 'भाषा बदलें',
      'english': 'अंग्रेज़ी',
      'hindi': 'हिंदी',
      'gujarati': 'ગુજરાતી',
      'purchase_order': 'खरीद फरोख्त',
      'design_details': 'डिज़ाइन विवरण',
      'select_design': 'डिज़ाइन चुनें',
      'browse_design': 'डिज़ाइन ब्राउज़ करें',
      'search_design': 'डिज़ाइन खोजें',
      'search_design_by': 'नाम या नंबर से डिज़ाइन खोजें...',
      'design_name': 'डिज़ाइन का नाम',
      'enter_design_name': 'डिज़ाइन का नाम दर्ज करें',
      'design_number': 'डिज़ाइन नंबर',
      'enter_design_number': 'डिज़ाइन नंबर दर्ज करें (उदा.: WF-100)',
      'design_image': 'डिज़ाइन की छवि',
      'tap_to_upload_photo': 'फोटो अपलोड करने के लिए टैप करें',
      'submit_design': 'डिज़ाइन सबमिट करें',
      'party_details': 'पार्टी का विवरण',
      'browse_party': "पार्टी ब्राउज़ करें",
      'select_party': 'पार्टी चुनें',
      'search_parties': 'पार्टी खोजें',
      'search_party_by': 'नाम या GST द्वारा पार्टी खोजें...',
      'party_name': 'पार्टी का नाम',
      'enter_party_name': 'पार्टी का नाम दर्ज करें',
      'party_number': 'पार्टी नंबर',
      'enter_party_number': 'पार्टी नंबर दर्ज करें (उदा.: WF-100)',
      'gst_number': 'GST नंबर',
      'enter_gst_number': 'GST नंबर दर्ज करें',
      'phone_number': 'फोन नंबर',
      'enter_phone_number': 'फोन नंबर दर्ज करें',
      'email': 'ईमेल',
      'enter_email_address': 'ईमेल पता दर्ज करें',
      'address': 'पता',
      'enter_full_address': 'पूरा पता दर्ज करें',
      'brokers_name': 'ब्रोकर का नाम',
      'enter_broker_name': 'ब्रोकर का नाम दर्ज करें',
      'submit_party': 'पार्टी सबमिट करें',
      'create_party': 'पार्टी बनाएं',
      'update_design': 'डिज़ाइन अपडेट करें',
      'remove_image': 'छवि निकालें',
      'update_party': 'पार्टी अपडेट करें',
      'delete_party': 'पार्टी हटाएं',
      'delete_design': 'डिज़ाइन हटाएं',
      'party_name_is_mandatory': 'पार्टी का नाम अनिवार्य है',
      'party_number_is_mandatory': 'पार्टी नंबर अनिवार्य है',
      'delete': 'हटाएं',

      'quality_specifications': 'गुणवत्ता विनिर्देश',
      'panna': 'पन्ना',
      'enter_panna_width': 'पन्ना की चौड़ाई दर्ज करें',
      'panna_is_required': 'पन्ना आवश्यक है।',
      'process': 'प्रक्रिया',
      'dyeing_printing': 'जैसे, रंगाई, छपाई',
      'order_details': 'ऑर्डर विवरण',
      'quantity': 'मात्रा',
      'enter_total_quantity': 'कुल मात्रा दर्ज करें',
      'quantity_must_be_greater_than_0': 'मात्रा 0 से अधिक होनी चाहिए।',
      'rate': 'दर',
      'enter_rate_per_unit': 'प्रति इकाई दर दर्ज करें',
      'party_po_number': 'पार्टी पीओ नंबर',
      'enter_partys_po_number': 'पार्टी का पीओ नंबर दर्ज करें',
      'delivery_date': 'डिलीवरी की तारीख',
      'select_delivery_date': 'डिलीवरी की तारीख चुनें',
      'high_priority': 'उच्च प्राथमिकता',
      'save_order': 'ऑर्डर सहेजें',

      'pending': 'लंबित',
      'in_progress': 'प्रगति पर',
      'ready_to_dispatch': 'डिस्पैच के लिए तैयार',
      'completed': 'पूर्ण',
      'customer': 'ग्राहक',
      'customer_id': 'ग्राहक आईडी',

      'edit': 'संपादित करें',
      'home': 'होम',
      'po_list': 'पीओ सूची',
      'create_po': 'पीओ बनाएं',
      'profile': 'प्रोफ़ाइल',

      'firm_name': 'फर्म का नाम',
      'moved_by': 'द्वारा ले जाया गया',
      'machine_no': 'मशीन नंबर',
      'delivered': 'वितरित',
      'calculator': 'कैलकुलेटर',

      'warp': 'ताना',
      'weft': 'बाना',
      'labour': 'श्रम',
      'total_warp_cost': 'कुल ताना लागत',
      'quality': 'गुणवत्ता',
      'denier': 'डेनियर',
      'tar': 'तार',
      'meter': 'मीटर',
      'rate_per_kg': 'प्रति किलो दर',
      'save_and_next': 'सहेजें और अगला',
      'quality_required': 'गुणवत्ता फ़ील्ड आवश्यक है।',
      'denier_required': 'डेनियर फ़ील्ड आवश्यक है।',
      'tar_required': 'तार फ़ील्ड आवश्यक है।',
      'meter_required': 'मीटर फ़ील्ड आवश्यक है।',
      'rate_per_kg_required': 'प्रति किलो दर आवश्यक है।',
      'design_card': 'डिज़ाइन कार्ड',
      'design_card_required': 'डिज़ाइन कार्ड फ़ील्ड आवश्यक है।',
      'enter_paisa': 'पैसा दर्ज करें',
      'paisa': 'पैसा',
      'cost': 'लागत',
      'no_data_found': 'कोई डेटा नहीं मिला',
      'feeder': 'फीडर',
      'pick': 'पिक',
      'panno': 'पन्नो',
      'atleast_one_feeder_is_required': 'कम से कम एक फीडर आवश्यक है।',
      'only_12_feeders_are_allowed': 'केवल 12 फीडर की अनुमति है।',
      'users': 'उपयोगकर्ता',
      'add_user': 'उपयोगकर्ता जोड़ें',
      'edit_user': 'उपयोगकर्ता संपादित करें',

      'logout': 'लॉग आउट',
      'confirm_logout': 'क्या आप वाकई लॉग आउट करना चाहते हैं?',
      'cancel': 'रद्द करें',
      'password': 'पासवर्ड',
      'enter_password': 'अपना पासवर्ड दर्ज करें',
      'login_with_username_and_password':
          'उपयोगकर्ता नाम और पासवर्ड के साथ लॉगिन करें।',

      'is_active': 'सक्रिय है',
      'name': 'नाम',
      'phone': 'फोन',
      'create': 'बनाएं',
      'update': 'अपडेट करें',
      'edit_user_details': 'उपयोगकर्ता विवरण संपादित करें',
      'select_role': 'भूमिका चुनें',
      'user_role': 'उपयोगकर्ता भूमिका',
      'confirm': 'पुष्टि करें',
      'no': 'नहीं',
      'order_type': 'ऑर्डर प्रकार',
      'job_po': 'जॉब पीओ',
      'order_quantity': 'ऑर्डर मात्रा',
      'pending_quantity': 'लंबित मात्रा',
      'in_process_quantity': 'प्रगति में मात्रा',

      'ready_to_dispatch_quantity': 'डिस्पैच के लिए तैयार मात्रा',
      'completed_quantity': 'पूर्ण मात्रा',
      'delivered_quantity': 'वितरित मात्रा',
      'note': 'नोट',

      'firms': 'फर्म',
      'add_firm': 'फर्म जोड़ें',
      'edit_firm': 'फर्म संपादित करें',
      'firm_enter_name': 'फर्म का नाम दर्ज करें',
      'firm_name_required': 'फर्म का नाम आवश्यक है।',

      'delete_firm': 'फर्म हटाएं',
      'are_you_sure_you_want_to_delete_firm':
          'क्या आप वाकई फर्म हटाना चाहते हैं?',
      'history': 'इतिहास',
    },

    'gu_IN': {
      'language_change': 'ભાષા બદલો',
      'english': 'અંગ્રેજી',
      'hindi': 'હિન્દી',
      'gujarati': 'ગુજરાતી',
      'purchase_order': 'ખરીદ ઓર્ડર',
      'design_details': 'ડિઝાઇન વિગતો',
      'select_design': 'ડિઝાઇન પસંદ કરો',
      'browse_design': 'ડિઝાઇન બ્રાઉઝ કરો',
      'search_design': 'ડિઝાઇન શોધો',
      'search_design_by': 'નામ અથવા નંબર દ્વારા ડિઝાઇન શોધો...',
      'design_name': 'ડિઝાઇનનું નામ',
      'enter_design_name': 'ડિઝાઇનનું નામ દાખલ કરો',
      'design_number': 'ડિઝાઇન નંબર',
      'enter_design_number': 'ડિઝાઇન નંબર દાખલ કરો (દા.ત.: WF-100)',
      'design_image': 'ડિઝાઇન છબી',
      'tap_to_upload_photo': 'ફોટો અપલોડ કરવા માટે ટેપ કરો',
      'submit_design': 'ડિઝાઇન સબમિટ કરો',
      'party_details': 'પાર્ટીની વિગતો',
      'browse_party': "પાર્ટી બ્રાઉઝ કરો",
      'select_party': 'પાર્ટી પસંદ કરો',
      'search_parties': 'પાર્ટીઓ શોધો',
      'search_party_by': 'નામ અથવા GST દ્વારા પાર્ટીઓ શોધો...',
      'party_name': 'પાર્ટીનું નામ',
      'enter_party_name': 'પાર્ટીનું નામ દાખલ કરો',
      'party_number': 'પાર્ટી નંબર',
      'enter_party_number': 'અનન્ય પાર્ટી નંબર દાખલ કરો (દા.ત. WF-100)',
      'gst_number': 'GST નંબર',
      'enter_gst_number': 'GST નંબર દાખલ કરો',
      'phone_number': 'ફોન નંબર',
      'enter_phone_number': 'ફોન નંબર દાખલ કરો',
      'email': 'ઈમેલ',
      'enter_email_address': 'ઈમેલ એડ્રેસ દાખલ કરો',
      'address': 'સરનામું',
      'enter_full_address': 'પૂરું સરનામું દાખલ કરો',
      'brokers_name': 'બ્રોકરનું નામ',
      'enter_broker_name': 'બ્રોકરનું નામ દાખલ કરો',
      'submit_party': 'પાર્ટી સબમિટ કરો',
      'create_party': 'પાર્ટી બનાવો',
      'update_design': 'ડિઝાઇન અપડેટ કરો',
      'remove_image': 'છબી દૂર કરો',
      'update_party': 'પાર્ટી અપડેટ કરો',
      'delete_party': 'પાર્ટી કાઢી નાખો',
      'delete_design': 'ડિઝાઇન કાઢી નાખો',
      'party_name_is_mandatory': 'પાર્ટીનું નામ ફરજિયાત છે',
      'party_number_is_mandatory': 'પાર્ટી નંબર ફરજિયાત છે',
      'delete': 'કાઢી નાખો',

      'quality_specifications': 'ગુણવત્તા સ્પષ્ટીકરણો',
      'panna': 'પન્ના',
      'enter_panna_width': 'પન્નાની પહોળાઈ દાખલ કરો',
      'panna_is_required': 'પન્ના જરૂરી છે.',
      'process': 'પ્રક્રિયા',
      'dyeing_printing': 'દા.ત., રંગાઈ, છાપકામ',
      'order_details': 'ઓર્ડર વિગતો',
      'quantity': 'જથ્થો',
      'enter_total_quantity': 'કુલ જથ્થો દાખલ કરો',
      'quantity_must_be_greater_than_0': 'જથ્થો 0 કરતાં વધુ હોવો જોઈએ.',
      'rate': 'દર',
      'enter_rate_per_unit': 'પ્રતિ એકમ દર દાખલ કરો',
      'party_po_number': 'પાર્ટી પીઓ નંબર',
      'enter_partys_po_number': 'પાર્ટીનો પીઓ નંબર દાખલ કરો',
      'delivery_date': 'ડિલિવરી તારીખ',
      'select_delivery_date': 'ડિલિવરી તારીખ પસંદ કરો',
      'high_priority': 'ઉચ્ચ અગ્રતા',
      'save_order': 'ઓર્ડર સાચવો',

      'pending': 'બાકી',
      'in_progress': 'પ્રગતિમાં',
      'ready_to_dispatch': 'રવાના થવા માટે તૈયાર',
      'completed': 'પૂર્ણ',
      'customer': 'ગ્રાહક',
      'customer_id': 'ગ્રાહક આઈડી',

      'edit': 'સંપાદિત કરો',
      'home': 'હોમ',
      'po_list': 'પીઓ યાદી',
      'create_po': 'પીઓ બનાવો',
      'profile': 'પ્રોફાઇલ',

      'firm_name': 'પેઢીનું નામ',
      'moved_by': 'દ્વારા ખસેડાયું',
      'machine_no': 'મશીન નંબર',

      'delivered': 'પહોંચાડાયું',
      'calculator': 'કેલ્ક્યુલેટર',

      'warp': 'તાણ',
      'weft': 'વણાટ',
      'labour': 'મજૂરી',
      'total_warp_cost': 'કુલ તાણ ખર્ચ',
      'quality': 'ગુણવત્તા',
      'denier': 'ડેનિયર',
      'tar': 'તાર',
      'meter': 'મીટર',
      'rate_per_kg': 'પ્રતિ કિલોગ્રામ દર',
      'save_and_next': 'સાચવો અને આગળ',

      'quality_required': 'ગુણવત્તા ક્ષેત્ર જરૂરી છે.',
      'denier_required': 'ડેનિયર ક્ષેત્ર જરૂરી છે.',
      'tar_required': 'તાર ક્ષેત્ર જરૂરી છે.',
      'meter_required': 'મીટર ક્ષેત્ર જરૂરી છે.',
      'rate_per_kg_required': 'પ્રતિ કિલોગ્રામ દર જરૂરી છે.',
      'design_card': 'ડિઝાઇન કાર્ડ',
      'design_card_required': 'ડિઝાઇન કાર્ડ ક્ષેત્ર જરૂરી છે.',
      'enter_paisa': 'પૈસા દાખલ કરો',
      'paisa': 'પૈસા',
      'cost': 'ખર્ચ',
      'no_data_found': 'કોઈ ડેટા મળ્યો નથી',
      'feeder': 'ફીડર',
      'pick': 'પિક',
      'panno': 'પન્નો',
      'atleast_one_feeder_is_required': 'કમ સે કમ એક ફીડર જરૂરી છે.',
      'only_12_feeders_are_allowed': 'ફક્ત 12 ફીડર્સની મંજૂરી છે.',
      'users': 'વપરાશકર્તાઓ',
      'add_user': 'વપરાશકર્તા ઉમેરો',
      'edit_user': 'વપરાશકર્તા સંપાદિત કરો',

      'logout': 'લૉગ આઉટ',
      'confirm_logout': 'શું તમે ખરેખર લૉગ આઉટ કરવા માંગો છો?',
      'cancel': 'રદ કરો',
      'password': 'પાસવર્ડ',
      'enter_password': 'તમારો પાસવર્ડ દાખલ કરો',
      'login_with_username_and_password':
          'વપરાશકર્તા નામ અને પાસવર્ડ સાથે લૉગિન કરો.',
      'is_active': 'સક્રિય છે',
      'name': 'નામ',
      'phone': 'ફોન',
      'create': 'બનાવો',
      'update': 'અપડેટ કરો',
      'edit_user_details': 'વપરાશકર્તા વિગતો સંપાદિત કરો',
      'select_role': 'ભૂમિકા પસંદ કરો',
      'user_role': 'વપરાશકર્તા ભૂમિકા',
      'confirm': 'પુષ્ટિ કરો',
      'no': 'ના',
      'order_type': 'ઓર્ડર પ્રકાર',
      'job_po': 'જોબ પીઓ',
      'order_quantity': 'ઓર્ડર જથ્થો',
      'pending_quantity': 'બાકી જથ્થો',
      'in_process_quantity': 'પ્રગતિમાં જથ્થો',
      'ready_to_dispatch_quantity': 'રવાના થવા માટે તૈયાર જથ્થો',
      'completed_quantity': 'પૂર્ણ જથ્થો',
      'delivered_quantity': 'પહોંચાડાયેલું જથ્થો',
      'note': 'નોંધ',

      'firms': 'ફર્મ',
      'add_firm': 'ફર્મ ઉમેરો',
      'edit_firm': 'ફર્મ સંપાદિત કરો',
      'firm_enter_name': 'ફર્મનું નામ દાખલ કરો',
      'firm_name_required': 'ફર્મનું નામ જરૂરી છે.',
      'delete_firm': 'ફર્મ કાઢી નાખો',
      'are_you_sure_you_want_to_delete_firm':
          'શું તમે ખરેખર ફર્મ કાઢી નાખવા માંગો છો?',
      'history': 'ઇતિહાસ',
    },
  };
}
